### ISSUE TITLE
Diff output support for event type components

### ISSUE THREAD

**Issue by lrmondigo** [Accenture/sfpowerkit#196]
Using `sfpowerkit:project:diff`, I had changes on event type components. The generation of the diff works fine but the event file doesn't show up on the output list.

![image](https://user-images.githubusercontent.com/48669617/73334055-90d36980-42a6-11ea-9881-c80720b2d740.png)

**Comment by genoud** [comment]
This is because the log display by default file that changed. The other file is copied because it is the associated file without which the deployment will not work. 
If you want to see those files, set the log level to **trace** and you will see all associated files copied along with the changed file.

**Comment by genoud** [comment]
I misunderstood the issue. Just pushed a fix
