### ISSUE TITLE
Include user permissions in profile retrive

### ISSUE THREAD

**Issue by EstebanRomero84** [Accenture/sfpowerkit#291]
**Describe the bug**
When retrieving a profile with sfpowerkit:source:profile:retrieve, the xml file doesn't include the user permissions.

**Expected behavior**
Include user permissions in profile retrieve.

**Comment by azlam-abdulsalam** [comment]
@EstebanRomero84 Can you provide more details? Retrieve does include user permissions

**Comment by EstebanRomero84** [comment]
Hi @azlam-abdulsalam I'm connected to a sandbox and executed this command:

`sfdx sfpowerkit:source:profile:retrieve  -f force-app -n "Admin" --loglevel=debug`

The retrieve xml file include all other permissions, but not User Permissions (<userPermissions>)

After that, I executed a retrieve using a package.xml to retrieve that profile, and it does include User Permissions

I'm running sfpowerkit 1.44.2 version

Regards

**Comment by genoud** [comment]
Hello @EstebanRomero84 
We did not include user permissions for Standard profiles (Admin, Standard User...)  as those permissions are not editable from user interface in Salesforce.

**Comment by TomSesselmann** [comment]
Hi @genoud, @azlam-abdulsalam  I want to re-open this issue because there are in fact some user permissions that are editable in standard profiles.

- Is Single Sign-On Enabled
- View Global Header

That's all I can see in my org.

I don't know if being able to edit these user permissions on standard profiles is a recent change or not.

![Screen Shot 2022-07-08 at 6 47 18 pm](https://user-images.githubusercontent.com/23013276/177955718-967e9fe6-b896-4d28-9838-91a06f3af4c4.png)
![Screen Shot 2022-07-08 at 6 47 31 pm](https://user-images.githubusercontent.com/23013276/177955738-1a111d8a-2e38-4d90-b6d5-0727349429de.png)
