### ISSUE TITLE
Retrieve full permission set xml file the same way it does for profile files

### ISSUE THREAD

**Issue by EstebanRomero84** [Accenture/sfpowerkit#292]
**Is your feature request related to a problem? Please describe.**
Allow to execute a persmission set retrieve that include all permissions, the same way it works for profiles.

**Comment by azlam-abdulsalam** [comment]
Can you elaborate on the use case here
Profile command exists as permissions on profiles as well as various other parameters differs by environments. So its hard to version control. Where as permsets is easy and manageable and doesnt differ per org. They are easy to transport from left to right

**Comment by EstebanRomero84** [comment]
Hi @azlam-abdulsalam - when we started using a vcs some time ago, we performed a full retrieve of all components from PROD to do the initial commit. So, in the case of permsets, they included permissions for all components, whether it gives access to them or not.

Now, when we retrieve a permset from a sandbox, it only includes permissions for the components that it does give access to. We have cases where the permset in the repo has 20,000 lines and the retrieved one only 50 lines.

Maybe this is too specific for our use case. Do you have any recommendation for this?

**Comment by genoud** [comment]
Hello @EstebanRomero84,

This behaviour is due to the change that Salesforce made on the PermissionSet Metadata in API 40. https://releasenotes.docs.salesforce.com/en-us/summer17/release-notes/rn_forcecom_permission_metadata_behavior.htm.
Since then, Deploying a permission Set replace the configuration of that permission Set in the target Org. Before the change, the Permission Set was Merged. That make it useless to keep track on configurations that remove access in PermissionSet Metadata. 

That said, I think you can update your VCS with the new version of your permission Set that only contains configurations that give access.

Thanks
