### ISSUE TITLE
sfdx sfpowerkit:source:pmd returning error "##[error]Bash exited with code '4'" after updating --report to --reportfile

### ISSUE THREAD

**Issue by allisonarnaud** [Accenture/sfpowerkit#540]
**Describe the bug**
When we updated "--report" to "--reportfile" to comply with "--report" deprecation for the command "sfdx sfpowerkit:source:pmd", our PR validation pipelines are now returning an error not previously seen, saying "##[error]Bash exited with code '4'" (see screenshot below), preventing the PMD check to complete.

Note: this was tested locally and the issue did not come up.

**To Reproduce**
Run command "sfdx sfpowerkit:source:pmd -f csv --report pmd-output.csv"

**Expected behavior**
PMD check validated, or not, based on code quality.

**Screenshots**
![image](https://user-images.githubusercontent.com/84055520/124062026-59588600-da73-11eb-97f9-9087160cf37b.png)

**Desktop (please complete the following information):**

- OS: Linux Ubuntu 20.04
- Version of sfpowerkit: v3.1.5

**Comment by Caitlyn-Mills** [comment]
@rody Any other reports of this behaviour?

**Comment by rody** [comment]
Yes, that's an expected behavior.
After an analysis is complete, PMD exits with different exit code (see https://pmd.github.io/latest/pmd_userdocs_cli_reference.html for more details).

An exit code of 4 means that at least one violation has been found. Those exit codes are very useful for scripting (no need to parse the report file to detect if there was a violation).

If you only want to create a reportfile and don't care about the exit code, you can use the flag "--no-failonviolation" which will tell PMD to always return 0 as the exit code.

**Comment by Caitlyn-Mills** [comment]
Thanks @rody appreciate the speedy response.
