### ISSUE TITLE
Problem with special characters in file names.

### ISSUE THREAD

**Issue by lDante93** [Accenture/sfpowerkit#583]
Hello. 
I've discovered that some of my classes aren't added properly for CI/CD processes using sfdx sfpowerkit:project:diff command. When I have checked my commits included in Pull Request with git diff command, everything worked properly and all files were included, hovewer project diff created with sfpowerkits does not included all of the files. I have found that files that are not included have special characters (in my case polish characters) in the name.

I've done a little test which shows my problem:
1. Add to layout special characters such as: "óążźćś"
2. git diff HEAD~1  --name-only
3. sfdx sfpowerkit:project:diff -r HEAD~1 --output srcDelta

**Expected behavior**
sfpowerkits should create proper diff with all files.

**Screenshots**
![sfpowerkits problem](https://user-images.githubusercontent.com/17831753/136760372-f4f29ad6-a724-4202-ab69-cb78742c5c5e.jpg)

**Desktop**
- OS: Windows/Linux
- sfdx-cli/7.117.0 win32-x64 node-v14.17.6
- @dxatscale/sfpowerscripts 8.4.0

**Comment by henry88lay** [comment]
Hi @genoud,
Any updates on this ticket?

**Comment by maelmonnier** [comment]
Hello,

We have at our company the same problem with french special characters in our layouts filenames (for example with the "é" char). I saw that the command used to generate the diff is `git ls-tree`. In the output format section, the `-z` option is advised to avoid problems with "unusual" characters https://git-scm.com/docs/git-ls-tree, or to change the git configuration `core.quotePath`.

By putting the git configuration `core.quotePath` to `false`, the problem is resolved (see https://git-scm.com/docs/git-config#Documentation/git-config.txt-corequotePath)

But we have not tested this fix during a long enough time, so we do not know if it can break other things.

**Comment by genoud** [comment]
Hi @henry88lay and @maelmonnier 
Can you test this fix?
Thanks

**Comment by henry88lay** [comment]
Awesome stuff I will get this tested from my end @genoud

**Comment by maelmonnier** [comment]
> Hi @henry88lay and @maelmonnier Can you test this fix #663 Thanks

Hi @genoud,
Sorry the delay. We have some trouble in our company due to HTTPS proxy and certificates, and could not update the plugin. I have updated it successfully today, and I confirm that the issue is resolved. Thanks.
